//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace cfg
{ 
    public enum AnimationType
    {
        /// <summary>
        /// 闲置动画
        /// </summary>
        Idel = 0,
        /// <summary>
        /// 移动动画
        /// </summary>
        Move = 1,
        /// <summary>
        /// 攻击动画
        /// </summary>
        Attack = 2,
        /// <summary>
        /// 死亡动画
        /// </summary>
        Die = 3,
        /// <summary>
        /// 技能动画1
        /// </summary>
        Skill1 = 4,
        /// <summary>
        /// 技能动画2
        /// </summary>
        Skill2 = 5,
        /// <summary>
        /// 技能动画3
        /// </summary>
        Skill3 = 6,
        /// <summary>
        /// 技能动画4
        /// </summary>
        Skill4 = 7,
        /// <summary>
        /// 技能动画5
        /// </summary>
        Skill5 = 8,
        /// <summary>
        /// 技能动画6
        /// </summary>
        Skill6 = 9,
        /// <summary>
        /// 技能动画7
        /// </summary>
        Skill7 = 10,
    }

} 
