//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace cfg
{ 
    public enum AttributeType
    {
        /// <summary>
        /// 最大移动速度
        /// </summary>
        MaxSpeed = 1,
        /// <summary>
        /// 碰撞体积
        /// </summary>
        Radius = 2,
        /// <summary>
        /// 忽略碰撞层级
        /// </summary>
        LayerIgnore = 3,
        /// <summary>
        /// 可以与哪些层级碰撞
        /// </summary>
        LayerOccupation = 4,
        /// <summary>
        /// 0禁用 1启用
        /// </summary>
        CollisionEnabled = 5,
        /// <summary>
        /// 0禁用 1启用
        /// </summary>
        RVOEnable = 6,
        /// <summary>
        /// 模型旋转速度
        /// </summary>
        RotSpeed = 7,
        /// <summary>
        /// 实例化出来的时候初始状态
        /// </summary>
        InitState = 8,
        /// <summary>
        /// 所属Team
        /// </summary>
        Team = 9,
        /// <summary>
        /// 状态机所有状态
        /// </summary>
        EntityStates = 10,
        /// <summary>
        /// 最大血量
        /// </summary>
        MaxHp = 11,
        /// <summary>
        /// 攻击间隔(单位秒)
        /// </summary>
        AttackInterval = 12,
        /// <summary>
        /// 攻击速度加成(1+x)
        /// </summary>
        AttackSpeed = 13,
        /// <summary>
        /// 攻击距离要比碰撞大才行
        /// </summary>
        AttackRadius = 14,
        /// <summary>
        /// 实体攻击力
        /// </summary>
        Attack = 15,
        /// <summary>
        /// 实体攻击类型
        /// </summary>
        AttackType = 16,
    }

} 
