//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace cfg
{ 
    public enum ComponentType
    {
        /// <summary>
        /// 拥有避障功能
        /// </summary>
        EntityRVOAgentComponentData = 1,
        /// <summary>
        /// 拥有移动看向目标功能
        /// </summary>
        EntityLookupComponentData = 2,
        /// <summary>
        /// 拥有属性功能
        /// </summary>
        EntityAttributeComponentData = 3,
        /// <summary>
        /// 拥有状态
        /// </summary>
        EntityStateComponentData = 4,
        /// <summary>
        /// 可以被搜索
        /// </summary>
        EntitySearchTag = 5,
        /// <summary>
        /// 可以用于显示血条
        /// </summary>
        HpBarComponentData = 6,
    }

} 
