//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace cfg
{ 
    public enum EntityAttackType
    {
        /// <summary>
        /// 单体攻击
        /// </summary>
        Type1 = 1,
    }

} 
