//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace cfg
{ 
    public enum EntityState
    {
        /// <summary>
        /// 闲置状态
        /// </summary>
        Idel = 1,
        /// <summary>
        /// 移动状态
        /// </summary>
        Move = 2,
        /// <summary>
        /// 攻击状态
        /// </summary>
        Attack = 4,
        /// <summary>
        /// 死亡状态
        /// </summary>
        Die = 8,
    }

} 
