//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace cfg
{ 
    public enum EntityTeam
    {
        /// <summary>
        /// 部队tag
        /// </summary>
        Team1 = 1,
        /// <summary>
        /// 部队tag
        /// </summary>
        Team2 = 2,
        /// <summary>
        /// 部队tag
        /// </summary>
        Team3 = 3,
        /// <summary>
        /// 部队tag
        /// </summary>
        Team4 = 4,
        /// <summary>
        /// 部队tag
        /// </summary>
        Single = 5,
    }

} 
