//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace cfg
{ 
    [System.Flags]
    public enum GridType
    {
        /// <summary>
        /// A*格子
        /// </summary>
        AStar = 1,
        /// <summary>
        /// 可放置格子
        /// </summary>
        Placeable = 2,
        /// <summary>
        /// 有建筑格子
        /// </summary>
        Building = 4,
    }

} 
