//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg.sceneConfigs
{ 

public sealed partial class TbSceneConfigs
{
    private readonly Dictionary<int, sceneConfigs.SceneConfigs> _dataMap;
    private readonly List<sceneConfigs.SceneConfigs> _dataList;
    
    public TbSceneConfigs(JSONNode _json)
    {
        _dataMap = new Dictionary<int, sceneConfigs.SceneConfigs>();
        _dataList = new List<sceneConfigs.SceneConfigs>();
        
        foreach(JSONNode _row in _json.Children)
        {
            var _v = sceneConfigs.SceneConfigs.DeserializeSceneConfigs(_row);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }

    public Dictionary<int, sceneConfigs.SceneConfigs> DataMap => _dataMap;
    public List<sceneConfigs.SceneConfigs> DataList => _dataList;

    public sceneConfigs.SceneConfigs GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public sceneConfigs.SceneConfigs Get(int key) => _dataMap[key];
    public sceneConfigs.SceneConfigs this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    
    partial void PostInit();
    partial void PostResolve();
}

}