//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg.audioConfig
{ 

public sealed partial class AudioConfig :  Bright.Config.BeanBase 
{
    public AudioConfig(JSONNode _json) 
    {
        { if(!_json["Id"].IsNumber) { throw new SerializationException(); }  Id = _json["Id"]; }
        { if(!_json["AudioGroup"].IsNumber) { throw new SerializationException(); }  AudioGroup = _json["AudioGroup"]; }
        { if(!_json["AudioName"].IsString) { throw new SerializationException(); }  AudioName = _json["AudioName"]; }
        PostInit();
    }

    public AudioConfig(int Id, int AudioGroup, string AudioName ) 
    {
        this.Id = Id;
        this.AudioGroup = AudioGroup;
        this.AudioName = AudioName;
        PostInit();
    }

    public static AudioConfig DeserializeAudioConfig(JSONNode _json)
    {
        return new audioConfig.AudioConfig(_json);
    }

    /// <summary>
    /// 这是id
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 音效组
    /// </summary>
    public int AudioGroup { get; private set; }
    /// <summary>
    /// 音效名字
    /// </summary>
    public string AudioName { get; private set; }

    public const int __ID__ = 916828258;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "AudioGroup:" + AudioGroup + ","
        + "AudioName:" + AudioName + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
