//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg.entityAttributeConfig
{ 

public sealed partial class TbEntityAttributeConfig
{
    private readonly Dictionary<long, entityAttributeConfig.EntityAttributeConfig> _dataMap;
    private readonly List<entityAttributeConfig.EntityAttributeConfig> _dataList;
    
    public TbEntityAttributeConfig(JSONNode _json)
    {
        _dataMap = new Dictionary<long, entityAttributeConfig.EntityAttributeConfig>();
        _dataList = new List<entityAttributeConfig.EntityAttributeConfig>();
        
        foreach(JSONNode _row in _json.Children)
        {
            var _v = entityAttributeConfig.EntityAttributeConfig.DeserializeEntityAttributeConfig(_row);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }

    public Dictionary<long, entityAttributeConfig.EntityAttributeConfig> DataMap => _dataMap;
    public List<entityAttributeConfig.EntityAttributeConfig> DataList => _dataList;

    public entityAttributeConfig.EntityAttributeConfig GetOrDefault(long key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public entityAttributeConfig.EntityAttributeConfig Get(long key) => _dataMap[key];
    public entityAttributeConfig.EntityAttributeConfig this[long key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    
    partial void PostInit();
    partial void PostResolve();
}

}