//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg.miscellaneousConfig
{ 

public sealed partial class TbMiscellaneousConfig
{
    private readonly Dictionary<int, miscellaneousConfig.MiscellaneousConfig> _dataMap;
    private readonly List<miscellaneousConfig.MiscellaneousConfig> _dataList;
    
    public TbMiscellaneousConfig(JSONNode _json)
    {
        _dataMap = new Dictionary<int, miscellaneousConfig.MiscellaneousConfig>();
        _dataList = new List<miscellaneousConfig.MiscellaneousConfig>();
        
        foreach(JSONNode _row in _json.Children)
        {
            var _v = miscellaneousConfig.MiscellaneousConfig.DeserializeMiscellaneousConfig(_row);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }

    public Dictionary<int, miscellaneousConfig.MiscellaneousConfig> DataMap => _dataMap;
    public List<miscellaneousConfig.MiscellaneousConfig> DataList => _dataList;

    public miscellaneousConfig.MiscellaneousConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public miscellaneousConfig.MiscellaneousConfig Get(int key) => _dataMap[key];
    public miscellaneousConfig.MiscellaneousConfig this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    
    partial void PostInit();
    partial void PostResolve();
}

}